name: Deploy Nexlearn

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Script
        run: echo "Deploying Nexlearn..."
